FROM critoma/amd64_u24_noble_ism_security

# TODO: Install Erlang (RabbitMQ dependency)
# TODO: Install RabbitMQ 4.2.5 from official RabbitMQ apt repo
# TODO: Enable RabbitMQ management plugin
# TODO: Copy definitions.json to pre-configure exchange, queue, and binding on startup
#       - Exchange: image.exchange (direct)
#       - Queue:    image.queue
#       - Binding:  routing key image.process

EXPOSE 5672 15672
