FROM critoma/amd64_u24_noble_ism_security

# TODO: Install OpenMPI, OpenSSL dev headers, gcc, libgomp (OpenMP)
# TODO: Install OpenSSH server
# TODO: Create /root/.ssh/ and copy MPI public key (mpi-keys/id_rsa.pub) to authorized_keys (chmod 600)
# TODO: Configure sshd: permit root login, disable password auth
# TODO: Entrypoint: start sshd in foreground

EXPOSE 22
