FROM critoma/amd64_u24_noble_ism_security

# TODO: Install Node.js 22 LTS
# TODO: Install MySQL 8.4.8 LTS from official MySQL apt repo
# TODO: Install MongoDB 8.0 LTS from official MongoDB apt repo
# TODO: Install supervisord (to manage mysqld, mongod, and node in one container)
# TODO: Copy supervisord.conf
# TODO: Copy Node.js app source and run npm install
# TODO: Copy MySQL init script (creates `images` table)
# TODO: Entrypoint: supervisord

EXPOSE 3001 3306 27017
