[supervisord]
logfile=/var/log/supervisor/supervisord.log

[program:mysqld]
command=/usr/sbin/mysqld
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mysqld.log
stderr_logfile=/var/log/supervisor/mysqld_err.log

[program:mongod]
command=/usr/bin/mongod
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mongod.log
stderr_logfile=/var/log/supervisor/mongod_err.log

[program:node]
command=/opt/software/nodejs/node-v22.21.0-linux-x64/bin/node /app/app.js
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/node.log
stderr_logfile=/var/log/supervisor/node_err.log
