FROM critoma/amd64_u24_noble_ism_security

# TODO: Install Node.js 22 LTS (for React build)
# TODO: Install JDK 25
# TODO: Install Maven
# TODO: Build React 19.2.4 frontend (npm run build)
# TODO: Build Spring Boot 4.0.5 JAR (mvn package)
# TODO: Serve React static files via Spring Boot (copy build output to resources/static)
# TODO: Run Spring Boot JAR as entrypoint

EXPOSE 3000 8080
